docker-deploy/web-app/firsthomework/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('rideshare/', include('rideshare.urls')),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='rideshare/', permanent=True)),
]

# Use static() to add URL mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

docker-deploy/web-app/rideshare/urls.py
from django.urls import path, include
from . import views

app_name = "rideshare"
urlpatterns = [
    # Can use reverse URL mapping such as: <a href="{% url 'index' %}">Home</a> to make a hyperlink to the page
    path('', views.index, name='index'),
    path('signup', views.signup, name='signup'),
    path('login', views.userLogin, name='login'),

    path("driver/register", views.DriverView.driverRegister, name="driverRegister"),
    path("driver/edit", views.DriverView.driverEdit, name="driverEdit"),
    path("driver/main", views.DriverView.driverMain, name="driverMain"),
    path("driver/search", views.DriverView.driverSearch, name="driverSearch"),
    path("<uuid:ride_id>/update/<str:status>", views.DriverView.updateRideStatus, name="updateRideStatus"),

    path("sharer/main", views.SharerView.sharerMain, name = "sharerMain"),
    path("sharer/search", views.SharerView.sharerSearch, name="sharerSearch"),
    path("sharer/<uuid:ride_id>/join", views.SharerView.shareJoin, name="sharerJoin"),
    path("sharer/<uuid:ride_id>/edit", views.SharerView.shareEdit, name="sharerEdit"),
    
    path('rides', views.RideListView.as_view(), name='rides'),
    path('rides/<uuid:pk>/', views.OwnerView.ride_detail_view, name='ride-detail'),

    path("owner/rides", views.OwnerView.owner_rides_view, name="owner-rides"),
    path("owner/request", views.OwnerView.owner_request_view, name="owner-request"),
    path("owner/edit/<uuid:ride_id>/", views.OwnerView.owner_edit_view, name="owner-edit"),
    path("owner/delete/<uuid:ride_id>/", views.OwnerView.owner_delete, name="owner-delete")
]

docker-deploy/web-app/rideshare/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Driver, Sharer, VehicleType, Ride

class DriverForm(forms.ModelForm):
    name = forms.CharField(required=True, label="Full Name", max_length=255, widget=forms.TextInput(attrs={'placeholder':"Enter your name"}))
    #vehicle_type = forms.CharField(required=True, label="Vehicle Type", max_length=20, widget=forms.TextInput(attrs={'placeholder':"Enter your vehicle type"}))
    vehicle_type = forms.ChoiceField(choices=[(item.value, item.name) for item in VehicleType])
    capacity = forms.IntegerField(required=True, label="Capacity") #widget=forms.TextInput(attrs={'placeholder':"Enter maximum number of passenger"})
    license_plate_number = forms.CharField(required=True, label="License Plate Number", max_length=20, widget=forms.TextInput(attrs={'placeholder':"Enter license plate number"}))
    special_vehicle_info = forms.CharField(required=False, label="Special Vehicle Info", widget=forms.Textarea(attrs={'placeholder':"Enter special vehicle info"}))

    class Meta:
        model = Driver
        exclude = ["user"]
        widgets = {'user': forms.HiddenInput()}
        labels = {
            "user": ""
        }

class SignupForm(UserCreationForm):
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder':"Username"}))
    password1 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'placeholder':"Password"}))
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'placeholder':"Password Confirmation"}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'placeholder':"Email Address"}))
    first_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder':"First Name"}))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder':"Last Name"}))
    
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email', 'first_name', 'last_name']

class SharerForm(forms.ModelForm):
    destination = forms.CharField(max_length=255)
    num_passengers = forms.IntegerField()
    earliest_arrival_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    latest_arrival_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    

    class Meta:
        model = Sharer
        fields = ['destination', 'num_passengers', 'earliest_arrival_time', 'latest_arrival_time']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Set a minimum value for num_passengers (adjust the value accordingly)
        self.fields['num_passengers'].widget.attrs['min'] = 1

class OwnerRequestForm(forms.ModelForm):
    destination = forms.CharField(required=True, label="Destination", max_length=255)
    
    num_passengers = forms.IntegerField(required=True, label="Number of Passengers")
    
    required_arrival_time = forms.DateTimeField(
        required=True,
        label="Required Arrival Time",
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
    )
   
    vehicle_type = forms.ChoiceField(
        choices=[(item.value, item.name) for item in VehicleType],
        required=True,
        label="Vehicle Type"
    )
    shared = forms.BooleanField(
        required=False,  
        initial=False, 
        label="Shared"
    )
    special_requests = forms.CharField(
        required=False,
        label="Special Requests",
        widget=forms.Textarea(attrs={'placeholder': "Enter special requests"}),
    )

    class Meta:
        model = Ride
        fields = [
            'destination',
            'num_passengers',
            'required_arrival_time',
            'vehicle_type',
            'shared',
            'special_requests',
        ]

class OwnerEditForm(forms.ModelForm):
    destination = forms.CharField(required=True, label="Destination", max_length=255)
    
    num_passengers = forms.IntegerField(required=True, label="Number of Passengers")
    
    required_arrival_time = forms.DateTimeField(
        required=True,
        label="Required Arrival Time",
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
    )
   
    vehicle_type = forms.ChoiceField(
        choices=[(item.value, item.name) for item in VehicleType],
        required=True,
        label="Vehicle Type"
    )
    shared = forms.BooleanField(
        required=False,  
        initial=False, 
        label="Shared"
    )
    special_requests = forms.CharField(
        required=False,
        label="Special Requests",
        widget=forms.Textarea(attrs={'placeholder': "Enter special requests"}),
    )

    class Meta:
        model = Ride
        fields = [
            'destination_address',
            'num_passengers',
            'required_arrival_time',
            'vehicle_type',
            'shared',
            'special_requests',
        ]

docker-deploy/web-app/rideshare/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.forms.models import model_to_dict
from django.contrib.auth import authenticate, login
from django.core.exceptions import ValidationError
from .models import User, Driver, Ride, RideStatus, Sharer
from .forms import SignupForm, DriverForm, SharerForm, OwnerEditForm, OwnerRequestForm

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, F, Value, IntegerField
from django.db.models.functions import Coalesce

import os.path
import base64

import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

import datetime
from django.utils import timezone



# Renders the HTML template with the data in the context variable
def signup(request):
    form = SignupForm()

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = SignupForm(request.POST)
        print(form.errors)

        # Check if the form is valid:
        if form.is_valid():
            print("valid")
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            user = form.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('rideshare:login') )

    # If this is a GET (or any other method) create the default form.       
    return render(request, 'signup.html', {'form': form})

def userLogin(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            
            # Redirect to a success page.
            return HttpResponseRedirect(reverse('rideshare:index') )
        else:
            messages.error(request,'username or password not correct')
            return HttpResponseRedirect(reverse(('rideshare:login')))
    return render(request, "login.html")

@login_required()
def index(request):
    """View function for home page of site."""
    user = request.user

    num_rides = Ride.objects.filter(owner_id=user.id).count()
    num_drivers = Driver.objects.filter(user=user).count()
    num_sharers = Sharer.objects.filter(user=user).count()


    context = {
        'num_rides': num_rides,
        'num_drivers': num_drivers,
        'num_sharers': num_sharers
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


def send_email(subject, to_email, html_content):
    try:
        sg = SendGridAPIClient('')
        message = Mail(
            from_email='alejandroyiweihe@gmail.com',
            to_emails=to_email,
            subject=subject,
            html_content=html_content
        )
        response = sg.send(message)
        print(response.status_code)
        print(response.body)
        print(response.headers)
    except Exception as e:
        print(f"Error sending email: {str(e)}")


# Driver
class DriverView(LoginRequiredMixin):

    @login_required()
    def updateRideStatus(request, ride_id, status):
        ride = get_object_or_404(Ride, pk = ride_id)
        driver = get_object_or_404(Driver, user=request.user)

        ride.status = status
        ride.driver = driver

        ride.save()

        if status == RideStatus.CONFIRMED.value:
            subject = "Ride Confirmed"
            to_email = ride.owner.email
            html_content = f"""
                    <h1>Dear {ride.owner.first_name} {ride.owner.last_name},</h1>
                    <h1>Your ride to {ride.destination_address} has been confirmed.</h1>
                    <h1>Your driver is {driver.name}.</h1>
                """
            send_email(subject, to_email, html_content)
        return HttpResponseRedirect(reverse('rideshare:driverMain'))

    @login_required()
    def driverRegister(request):
        user = request.user

        # Try to get the existing Driver instance, or create a new one if it doesn't exist
        try:
            driver = Driver.objects.get(user=user)
            form = DriverForm(instance=driver)
        except Driver.DoesNotExist:
            driver = None
            form = DriverForm()
        
        # If this is a POST request then process the Form data
        if request.method == 'POST':

            # Create a form instance and populate it with data from the request (binding):
            form = DriverForm(request.POST, instance=driver)

            # Check if the form is valid:
            if form.is_valid():
                form.instance.user = user
                driver = form.save()

                # redirect to a new URL:
                return HttpResponseRedirect(reverse('rideshare:driverMain') )

        # If this is a GET (or any other method) create the default form.       
        return render(request, "rideshare/driver/register.html", {'form': form})

    @login_required()
    def driverEdit(request):
        driver = get_object_or_404(Driver, user = request.user)
        form = DriverForm(instance=driver)

        # If this is a POST request then process the Form data
        if request.method == 'POST':

            # Create a form instance and populate it with data from the request (binding):
            form = DriverForm(request.POST, instance=driver)

            # Check if the form is valid:
            if form.is_valid():
                # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
                driver = form.save()

                # redirect to a new URL:
                return HttpResponseRedirect(reverse('rideshare:driverMain') )

        # If this is a GET (or any other method) create the default form.       
        return render(request, "rideshare/driver/edit.html", {'form': form})

    @login_required()
    def driverMain(request):
        if Driver.objects.filter(user=request.user).count() == 0:
            return HttpResponseRedirect(reverse('rideshare:driverRegister') )
        driver = get_object_or_404(Driver, user=request.user)
        #driver = Driver.objects.get(user=request.user)
        rides = Ride.objects.filter(driver=driver, status=RideStatus.CONFIRMED.value).order_by('required_arrival_time')
        complete_rides = Ride.objects.filter(driver=driver, status=RideStatus.COMPLETE.value).order_by('id')
        return render(request, "rideshare/driver/main.html", {'rides': rides, 'complete_rides': complete_rides})

    @login_required()
    def driverSearch(request):
        driver = get_object_or_404(Driver, user=request.user)
        if request.method == 'GET':
            if request.GET.get('arrival_time') == "":
                arrival_time = datetime.datetime.now()
            else:
                arrival_time_str = request.GET.get('arrival_time')
                arrival_time = datetime.datetime.strptime(arrival_time_str, "%Y-%m-%d %H:%M")
                
            if request.GET.get('passenger_count') == "":
                passenger_count = driver.capacity
            else:
                passenger_count = int(request.GET.get('passenger_count'))
            destination = request.GET.get('destination', "")

            if passenger_count > driver.capacity:
                passenger_count = driver.capacity
            

            #if passenger_count > driver.capacity:
            #    raise ValidationError("Passenger count exceed your vehicle's capacity.")

            # Perform your search logic based on form input
            results = Ride.objects.filter(
                required_arrival_time__gte=arrival_time,
                vehicle_type=driver.vehicle_type,
                status=RideStatus.OPEN.value,
                special_requests=driver.special_vehicle_info,
                destination_address__contains=destination,
            ).exclude(
                owner=driver.user
            )
            # .annotate(
            #     total_passengers=Coalesce(Sum('sharer__num_passengers'), Value(0), output_field=IntegerField())
            # ).filter(
            #     total_passengers__lte=F('driver__capacity') - F('num_passengers')
            # )
            print(results)

            return render(request, 'rideshare/driver/search.html', {'results': results})
        return render(request, "rideshare/driver/search.html")

# Owner
from django.views import generic
#class OwnerRideListView(generic.ListView):


class OwnerView(LoginRequiredMixin):
 
    def owner_rides_view(request):
        user = request.user
        owner_rides = user.rides_as_owner.all()
        return render(request, "rideshare/ride_list.html", {'ride_list': owner_rides})


    def owner_request_view(request):
        from .models import Ride  # Import the Ride model if not already imported

    def owner_request_view(request):
        user = request.user
        if request.method == 'POST':
            form = OwnerRequestForm(request.POST)
            if form.is_valid():
                new_ride = Ride(
                    destination_address=form.cleaned_data['destination'],
                    required_arrival_time=form.cleaned_data['required_arrival_time'],
                    vehicle_type=form.cleaned_data['vehicle_type'],
                    num_passengers=form.cleaned_data['num_passengers'],
                    shared=form.cleaned_data['shared'],
                    special_requests=form.cleaned_data['special_requests'],  
                    status=RideStatus.OPEN.value,
                    owner=user, 
                )

docker-deploy/web-app/rideshare/templates/base_generic.html
 <!-- Copied from developer.mozilla.org -->

 <!DOCTYPE html>
 <html lang="en">
 
 <head>
   {% block title %}
   <title>Ride Share</title>
   {% endblock %}
   <meta charset="utf-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1" />
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
     rel="stylesheet"
     integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
     crossorigin="anonymous">
   <!-- Add additional CSS in static file -->
   {% load static %}
   <link rel="stylesheet" href="{% static 'rideshare/css/style.css' %}" />
 </head>
 
 <body>
   <div class="container py-5">
     <div class="row">
       <div class="col-sm-2">
         {% block sidebar %}
         <nav class="sticky d-flex flex-column align-items-start justify-content-between h-90">
           <h3 class="userTitle">User: {{ user.get_username }}</h3>
           <ul class="mt-1 sidebar-nav menu-hover-fill flex flex-col items-start leading-none text-2xl uppercase space-y-4">
             <li class="mt-3"><a href="{% url 'rideshare:index'%}" data-text="Home">Home</a></li>
             <li class="mt-3"><a href="{% url 'rideshare:owner-rides'%}" data-text="As Owner">As Owner</a></li>
             <li class="mt-3"><a href="{% url 'rideshare:driverMain'%}" data-text="As Driver">As Driver</a></li>
             <li class="mt-3"><a href="{% url 'rideshare:sharerMain'%}" data-text="As Sharer">As Sharer</a></li>
           </ul>
           <br>
           <div class="mt-auto">
            <a href="{% url 'logout' %}?next={% url 'rideshare:login' %}" class="btn btn-info">Logout</a>
           </div>
          </nav>
         {% endblock %}
       </div>
       <div class="col-sm-10">
         {% block content %}
         {% endblock %}
       </div>
     </div>
   </div>
 </body>
 
 </html>
 

docker-deploy/web-app/rideshare/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'rideshare/css/index.css' %}">
</head>
  <h1>Ride Share</h1>
  <p>
    Welcome to Ride Share
  </p>
  <p>Choose from the left navigation bar to continue</p>
  <ul>
    <li><strong>As a owner, you have  {{ num_rides }} rides </strong> </li>
    <li><strong>As a driver, you have  {{ num_drivers}} rides </strong> </li>
    <li><strong>As a sharer, you have  {{ num_sharers }} rides </strong> </li>
  </ul>
{% endblock %}

docker-deploy/web-app/rideshare/templates/login.html
<!DOCTYPE html>
<html>

<head>
  <title>{% block title %}{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'rideshare/css/signup.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
  {% load bootstrap5 %}
  {% bootstrap_css %}
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
  <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
  {% bootstrap_javascript %}
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"></script>
</head>

<body>
  <div class="form-body">
    <div class="row">
      <div class="form-holder">
        {% for message in messages %}
        <div class="alert alert-success">
          <a class="close" href="#" data-dismiss="alert">×</a>
          {{ message }}
        </div>
        {% endfor %}

        <div class="form-content">
          <div class="form-items">
            <h3 class="text-center">Login</h3>

            {% if form.errors %}
            <div class="alert alert-danger">
              <strong>Error:</strong> Please fix the following issues.
              <ul>
                {% for field, errors in form.errors.items %}
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
                {% endfor %}
              </ul>
            </div>
            {% endif %}

            <form action="" method="post">
              {% csrf_token %}
              <div class="input-box col-md-12 mt-1">
                <span class="details"> Username </span>
                <input type="text" class="form-control search-slt" id="username" name="username"
                  placeholder="Enter Your Username">
              </div>
              <div class="input-box col-md-12 mt-1">
                <span class="details"> Password </span>
                <input type="text" class="form-control search-slt" id="password" name="password"
                  placeholder="Enter Your Password">
              </div>

              <div class="form-button mt-3">
                <button id="submit" type="submit" class="btn btn-secondary">Login</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

docker-deploy/web-app/rideshare/templates/signup.html
<!DOCTYPE html>
<html>

<head>
  <title>{% block title %}{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'rideshare/css/signup.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
  {% load bootstrap5 %}
  {% bootstrap_css %}
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
  <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
  {% bootstrap_javascript %}
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"></script>
</head>

<body>  
  <div class="form-body">
    <div class="row">
        <div class="form-holder">
            <div class="form-content">
                <div class="form-items">
                    <h3>Register Today</h3>
                    <p>Fill in the data below.</p>

                    {% if form.errors %}
                      <div class="alert alert-danger">
                        <strong>Error:</strong> Please fix the following issues.
                        <ul>
                          {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                              <li>{{ error }}</li>
                            {% endfor %}
                          {% endfor %}
                        </ul>
                      </div>
                    {% endif %}

                    <form action="" method="post">
                      {% csrf_token %}
                      {% for field in form %}
                      <div class="input-box col-md-12 mt-1">
                          {{ field }}
                      </div>
                      {% endfor %}

                      <div class="form-check input-box col-md-12 mt-3">
                        <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                        <label class="form-check-label">I confirm that all data are correct</label>
                      <div class="invalid-feedback">Please confirm that the entered data are all correct!</div>
                      </div>
                      

                      <div class="form-button mt-3">
                        <button id="submit" type="submit" class="btn btn-secondary">Register</button>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
  </div>
</body>

</html>